"""Source-informed parameterisation layer for the NZ primary care funding architecture models.

This module turns the earlier demonstrative model into a parameterised demonstrative run.
It does not claim empirical calibration. It links each normalised model lever to a public
input, an interpretation, a transformation rule, and a confidence rating. The run is designed
for decision support and validation planning.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Mapping, Sequence

import numpy as np
import pandas as pd

from .demonstrative_games import GAME_MODELS, Scenario
from .hybrid_model import hybrid_outcome
from .uncertainty import PARAMETER_FIELDS, perturb_scenario


@dataclass(frozen=True)
class ParameterInput:
    parameter: str
    domain: str
    interpretation: str
    public_input: str
    source_name: str
    source_url: str
    source_value: str
    transform_to_normalised: str
    current_normalised_value: float
    evidence_level: str
    confidence_0_to_1: float
    next_data_needed: str


# Values are source-informed priors, not calibrated coefficients.
PARAMETER_INPUTS: tuple[ParameterInput, ...] = (
    ParameterInput(
        "marginal_contact_benefit", "funding", "Public subsidy attached to additional eligible primary/urgent/ambulance contacts.",
        "NZ currently relies on capitation plus programme/ACC streams; no general MBS-style primary care benefits schedule exists.",
        "Ministry of Health capitation reweighting page and ACC provider payment page", "https://www.health.govt.nz/strategies-initiatives/programmes-and-initiatives/primary-and-community-health-care/capitation-reweighting | https://www.acc.co.nz/for-providers/invoicing-us/paying-patient-treatment",
        "Capitation is core general practice funding; ACC pays activity/contract/regulation-based injury treatment.",
        "Set current to 0.10 because marginal payment exists only partially via ACC/programmes and co-payments; benefits schedule scenarios increase this lever.",
        0.10, "public architecture + modelling judgement", 0.65, "Current capitation formula, ACC primary care claim volumes, programme funding and proposed benefit levels."
    ),
    ParameterInput(
        "capitation_weighting", "funding", "Adequacy of capitation weights for need, rurality, deprivation and multimorbidity.",
        "The current formula dates from 2002 and has had no major changes; reweighting will consider age, sex, multimorbidity, rurality and deprivation.",
        "Ministry of Health capitation reweighting", "https://www.health.govt.nz/strategies-initiatives/programmes-and-initiatives/primary-and-community-health-care/capitation-reweighting",
        "Formula introduced in 2002; new approach expected from 1 July 2026.",
        "Current pre-reweighting value set to 0.35; reweighting scenarios set to 0.75-0.85.",
        0.35, "public fact + modelling judgement", 0.80, "Full formula/rate tables, implementation modelling, and practice-level revenue effects."
    ),
    ParameterInput(
        "scope_flexibility", "workforce/scope", "Extent to which claimable primary care activity can be generated by providers acting within scope, not only GPs.",
        "ACC recognises GP, nurse and nurse-practitioner contributions for injury-related treatment; broader policy model would extend scope-based contact benefits.",
        "ACC paying providers", "https://www.acc.co.nz/for-providers/invoicing-us/paying-patient-treatment",
        "ACC contributes to consultation rates and procedures for GPs, nurses and nurse practitioners.",
        "Current value set to 0.35 to reflect partial scope use but GP-centred funding; scope-enabled scenarios set to 0.70-0.85.",
        0.35, "public architecture + modelling judgement", 0.55, "Provider workforce counts, scopes, prescribing rules, substitution studies, clinical governance models."
    ),
    ParameterInput(
        "pho_transaction_cost", "administration", "Friction, opacity or entry barrier from PHO-mediated funding and contracting.",
        "Current architecture still relies on PHO/service-agreement processes; transparency and pass-through issues require further evidence.",
        "Health NZ primary care health data; prior PHO review artefacts in repo", "https://www.healthnz.govt.nz/about-us/health-data/data-sets-and-collections/primary-care-data-and-statistics/primary-care-health-data",
        "Primary care data governance and SLM processes involve PHOs; closed-books availability is reported as a primary care indicator.",
        "Current set to 0.60; direct-claiming scenarios reduce to 0.15-0.30.",
        0.60, "public architecture + hypothesis", 0.45, "PHO financial flows, pass-through rules, provider onboarding timelines, direct claims costings."
    ),
    ParameterInput(
        "primary_kpi_salience", "accountability", "Political and managerial visibility of primary care access and outcomes.",
        "A primary care target will take effect from 1 July 2026, proposed as >80% access within one week.",
        "Ministry of Health primary care health target", "https://www.health.govt.nz/strategies-initiatives/programmes-and-initiatives/primary-and-community-health-care/primary-care-health-target",
        ">80% of people can access an appointment with a general practice provider within one week.",
        "Set current transitional value to 0.40 because target is announced but still being implemented; full architecture 0.85.",
        0.40, "public fact + modelling judgement", 0.80, "Final target definition, balancing measures, reporting frequency and consequence management."
    ),
    ParameterInput(
        "ambulance_kpi_salience", "accountability", "Visibility of ambulance response, demand, non-conveyance and alternative disposition outcomes.",
        "Ambulance providers report KPI data, including response times, demand, quality and call types, to the Ambulance Team.",
        "Health NZ Ambulance Team", "https://www.healthnz.govt.nz/about-us/what-we-do/programmes-and-initiatives/the-ambulance-team",
        "Monthly reports show response time KPIs, demand, quality of service and call type.",
        "Current set to 0.45 because ambulance KPIs exist but are not treated as hospital-equivalent top-tier system KPIs.",
        0.45, "public fact + modelling judgement", 0.75, "Alternative disposition, non-conveyance safety, offload delay and top-tier reporting status."
    ),
    ParameterInput(
        "hospital_political_penalty", "political economy", "Relative penalty for visible hospital failure compared with upstream access failure.",
        "Health NZ plans and commissions hospital, primary and community services; hospitals remain highly visible operationally.",
        "Ministry of Health Crown entities page", "https://www.health.govt.nz/about-us/new-zealands-health-system/health-system-roles-and-organisations/health-crown-entities",
        "Health NZ plans and commissions hospital, primary and community services.",
        "Set current to 0.90 as a strategic judgement; reduced only where upstream KPIs are top-tier and data visible.",
        0.90, "strategic modelling hypothesis", 0.45, "Budget decisions, media analysis, board papers, ministerial escalation patterns."
    ),
    ParameterInput(
        "data_observability", "data", "Ability to observe appointment access, unmet need, ambulance pathways, ED flow and avoidable hospitalisation links.",
        "NPCD begins with general practice encounter and appointment data, including booking, seen date and outcome, from April 2026.",
        "Health NZ National Primary Care Dataset", "https://www.healthnz.govt.nz/about-us/what-we-do/planning-and-performance/primary-care-tactical-action-plan/national-primary-care-dataset-and-new-primary-care-health-target",
        "Participating practices share encounter and appointment data from April 2026; first focus is the seven-day access target.",
        "Set transitional current to 0.45; full architecture 0.85 with linked primary, ambulance and hospital data.",
        0.45, "public fact + modelling judgement", 0.85, "Actual data completeness, PMS coverage, linkage to ED/ambulance/ASH and timeliness."
    ),
    ParameterInput(
        "copayment_level", "consumer price", "Patient price signal/private contribution to primary care utilisation.",
        "In 2024/25, 14.9% of adults reported not visiting a GP because of cost; Pacific and Māori adults reported higher cost barriers.",
        "NZ Health Survey 2024/25", "https://www.health.govt.nz/publications/annual-update-of-key-results-202425-new-zealand-health-survey",
        "Adults cost barrier 14.9%; Pacific adults 25.1%; Māori adults 18.7%.",
        "Normalise national adult cost barrier against a 25% high-burden benchmark: 14.9/25 ~= 0.60.",
        0.60, "public empirical input", 0.85, "Practice fee schedules, fee caps, CSC/VLCA eligibility and utilisation response by deprivation/ethnicity/rurality."
    ),
    ParameterInput(
        "copayment_protections", "consumer price", "Extent of targeted protection from co-payment barriers.",
        "Cost barriers remain material despite existing protections; Pacific, Māori and disabled adults have higher barriers.",
        "NZ Health Survey 2024/25", "https://www.health.govt.nz/publications/annual-update-of-key-results-202425-new-zealand-health-survey",
        "Cost barrier persisted at 14.9% nationally; Pacific 25.1%, Māori 18.7%; disabled adults had more access barriers.",
        "Set current to 0.45; full architecture 0.80 reflecting stronger concessions, caps and zero-fee contact types.",
        0.45, "public empirical input + modelling judgement", 0.70, "Distribution of fees and unmet need by group, patient-level frequent-user protection data."
    ),
    ParameterInput(
        "equity_program_strength", "equity", "Strength of kaupapa Māori, Pacific, outreach, locality, navigation and trust functions.",
        "Access barriers are higher for several high-need groups; equity functions must be preserved if direct benefits reduce intermediation.",
        "NZ Health Survey 2024/25", "https://www.health.govt.nz/publications/annual-update-of-key-results-202425-new-zealand-health-survey",
        "Pacific adults had highest GP cost barrier; disabled adults had more barriers including owing money, transport and support person.",
        "Set current to 0.60, reflecting existing but insufficient equity infrastructure; full architecture 0.85.",
        0.60, "public empirical input + modelling judgement", 0.60, "Kaupapa Māori/Pacific provider capacity, programme funding, outcomes by ethnicity/deprivation/disability/rurality."
    ),
    ParameterInput(
        "telehealth_scale", "digital access", "Extent of telehealth availability.",
        "Online and phone access are part of current Health NZ service pathways, but scale and substitution effects require data.",
        "Health NZ service pathways", "https://www.healthnz.govt.nz/about-us/health-data/data-sets-and-collections/primary-care-data-and-statistics/primary-care-health-data",
        "Online GP Care is mentioned as a performance-reporting example; exact volumes not yet in public calibration pack.",
        "Set current to 0.65; loose benefit scenario 0.90; full architecture keeps scale but improves integration.",
        0.65, "public architecture + modelling judgement", 0.40, "Telehealth volumes, rural uptake, substitution vs complementarity, continuity and safety outcomes."
    ),
    ParameterInput(
        "telehealth_integration", "digital access", "Integration of telehealth with local teams, records and in-person escalation.",
        "NPCD and Shared Digital Health Record work may improve integration, but data maturity is still developing.",
        "Health NZ primary care health data", "https://www.healthnz.govt.nz/about-us/health-data/data-sets-and-collections/primary-care-data-and-statistics/primary-care-health-data",
        "Shared Digital Health Record and NPCD are being developed; participation and data processes are evolving.",
        "Set current to 0.45; full architecture 0.80.",
        0.45, "public architecture + modelling judgement", 0.55, "Record-linkage coverage, escalation pathways, continuity metrics, safety events."
    ),
    ParameterInput(
        "local_inperson_loading", "rural/local supply", "Payment support for local and rural in-person capacity.",
        "Time to get an appointment is the largest reported GP barrier; rural/local in-person supply is a policy concern but not fully quantified here.",
        "NZ Health Survey 2024/25", "https://www.health.govt.nz/publications/annual-update-of-key-results-202425-new-zealand-health-survey",
        "25.5% of adults reported appointment wait time as a barrier.",
        "Set current to 0.25 given persistent wait-time barrier; full architecture 0.80 with explicit local/in-person loadings.",
        0.25, "public empirical input + modelling judgement", 0.60, "Rurality, travel time, local procedural/exam-dependent service data and practice viability by region."
    ),
    ParameterInput(
        "ambulance_alternative_funding", "ambulance", "Funding for hear-and-treat, treat-and-refer, non-conveyance and alternative destination pathways.",
        "Ambulance is commissioned by Health NZ and ACC; medical patients funded by Health NZ and injury patients by ACC.",
        "Health NZ Ambulance Team", "https://www.healthnz.govt.nz/about-us/what-we-do/programmes-and-initiatives/the-ambulance-team",
        "Emergency ambulance services are commissioned on behalf of Health NZ and ACC; medical and injury funding split.",
        "Set current to 0.35; ambulance-alternative scenario and full architecture to 0.75-0.80.",
        0.35, "public architecture + modelling judgement", 0.65, "Ambulance disposition data, non-conveyance safety, follow-up funding, ED avoidance rates."
    ),
    ParameterInput(
        "acc_activity_funding", "ACC", "Extent to which ACC activity payments stabilise primary/urgent care marginal supply.",
        "ACC pays based on regulations, contracts or purchase orders, including consultation and procedure contributions for GP/nurse/NP services.",
        "ACC paying providers", "https://www.acc.co.nz/for-providers/invoicing-us/paying-patient-treatment",
        "ACC contributes to consultation rates and specific treatment/procedure costs for GPs, nurses and nurse practitioners.",
        "Set current to 0.70; ACC constraint shock lowers to 0.45.",
        0.70, "public architecture + hypothesis", 0.55, "Practice revenue mix, claim volumes, provider response to ACC pricing, injury/non-injury cross-subsidy."
    ),
    ParameterInput(
        "acc_constraint", "ACC", "Degree of policy/pricing constraint on ACC activity funding.",
        "ACC provider payments are rules-based and activity-sensitive; constraining them may have cross-system effects.",
        "ACC paying providers", "https://www.acc.co.nz/for-providers/invoicing-us/paying-patient-treatment",
        "How ACC pays depends on service type and whether provider works under regulations, contract or purchase order.",
        "Set current to 0.10; ACC constraint shock 0.60; full architecture 0.00-0.05.",
        0.10, "public architecture + modelling hypothesis", 0.45, "Pricing changes, claim caps, provider exit/entry response, cross-funder spillover."
    ),
    ParameterInput(
        "budget_tightness", "fiscal", "Constraint imposed by fixed envelopes, baselines and deficit pressure.",
        "Health NZ plans/commissions hospitals, primary and community services; the model hypothesises upstream growth competes with hospital pressure.",
        "Ministry of Health Crown entities page", "https://www.health.govt.nz/about-us/new-zealands-health-system/health-system-roles-and-organisations/health-crown-entities",
        "Health NZ is responsible for planning and commissioning hospital, primary and community health services.",
        "Set current to 0.85; benefit-stream scenarios lower effective tightness because activity can expand within rules.",
        0.85, "strategic modelling hypothesis", 0.50, "Vote/baseline data, spending trends by service class, deficit response and reprioritisation evidence."
    ),
    ParameterInput(
        "safety_governance", "governance", "Clinical governance, credentialing, prescribing scope and audit for scope-enabled claiming.",
        "ACC requires appropriate qualifications/current practising certificate and acceptable quality/right time/place treatment.",
        "ACC paying providers", "https://www.acc.co.nz/for-providers/invoicing-us/paying-patient-treatment",
        "ACC payment conditions include appropriate qualifications, current practising certificate, quality and documentation.",
        "Set current to 0.75; full architecture 0.90; loose benefits 0.40.",
        0.75, "public architecture + modelling judgement", 0.70, "Credentialing model, prescribing/standing-order rules, adverse events, audit capacity."
    ),
    ParameterInput(
        "gaming_controls", "governance", "Audit, coding rules and balancing measures to prevent low-value activity and target gaming.",
        "NPCD and target governance include balancing measures; target design still needs confirmation.",
        "Health NZ primary care health data", "https://www.healthnz.govt.nz/about-us/health-data/data-sets-and-collections/primary-care-data-and-statistics/primary-care-health-data",
        "Advisory/governance groups will advise target definition, implementation and balancing measures.",
        "Set current to 0.60; full architecture 0.85; loose benefits 0.25.",
        0.60, "public architecture + modelling judgement", 0.65, "Coding rules, utilisation outliers, fraud/audit design, balancing measures, quality indicators."
    ),
    ParameterInput(
        "direct_claiming", "payment platform", "Ability for accredited providers to claim directly through a national rules-based platform.",
        "Current funding remains mediated through capitation/PHO/service arrangements; direct national claiming is the proposed architecture.",
        "Ministry of Health capitation; Health NZ primary care data", "https://www.health.govt.nz/strategies-initiatives/programmes-and-initiatives/primary-and-community-health-care/capitation-reweighting | https://www.healthnz.govt.nz/about-us/health-data/data-sets-and-collections/primary-care-data-and-statistics/primary-care-health-data",
        "Capitation is not paid directly to patients; PHO/governance structures remain central to data/funding arrangements.",
        "Set current to 0.05; direct-claims scenarios 0.75-0.90.",
        0.05, "public architecture + policy option", 0.60, "Platform specifications, credentialing, claims processing cost, provider onboarding and audit data."
    ),
    ParameterInput(
        "stakeholder_alignment", "political economy", "Coalition support across providers, PHOs, Māori/Pacific providers, ambulance, Health NZ, ACC and Treasury.",
        "No direct public calibration yet; stakeholder validation is required.",
        "Project validation plan", "internal", "Not yet measured.",
        "Set current to 0.35; improved where reform is coherent and preserves equity/locality functions.",
        0.35, "unvalidated judgement", 0.25, "Workshop scoring by stakeholder group; submissions; interviews."
    ),
    ParameterInput(
        "narrative_coherence", "political economy", "Clarity of reform narrative as access architecture rather than pro-market or sector income claim.",
        "No direct public calibration yet; communication testing is required.",
        "Project validation plan", "internal", "Not yet measured.",
        "Set current to 0.30; full architecture 0.85 if framed as access/hospital-avoidance and equity-protected.",
        0.30, "unvalidated judgement", 0.25, "Stakeholder/political discourse analysis and messaging tests."
    ),
)


def parameter_input_frame() -> pd.DataFrame:
    return pd.DataFrame([asdict(p) for p in PARAMETER_INPUTS])


_CURRENT = {p.parameter: p.current_normalised_value for p in PARAMETER_INPUTS}


def _scenario(scenario_id: str, name: str, description: str, **updates: float) -> Scenario:
    values = dict(_CURRENT)
    values.update(updates)
    missing = set(PARAMETER_FIELDS) - set(values)
    if missing:
        raise ValueError(f"missing parameter values: {missing}")
    return Scenario(scenario_id=scenario_id, name=name, description=description, **{k: float(values[k]) for k in PARAMETER_FIELDS})


PARAMETERISED_SCENARIOS: tuple[Scenario, ...] = (
    _scenario("P0", "Current source-informed baseline", "Current/public input baseline: capitation-centred, PHO-mediated, partial ACC/activity funding, imminent primary care target and developing NPCD."),
    _scenario("P1", "Capitation reweighting plus access target", "Reweight capitation and implement the access target/NPCD, but do not introduce a demand-driven contact benefit stream.",
              capitation_weighting=0.78, primary_kpi_salience=0.65, data_observability=0.60, copayment_level=0.55, copayment_protections=0.52, equity_program_strength=0.72, budget_tightness=0.78, stakeholder_alignment=0.45, narrative_coherence=0.45),
    _scenario("P2", "National Primary Care Benefits Schedule", "Defined primary/urgent/ambulance contact benefits, direct claiming, broader provider eligibility and moderate controls layered onto capitation.",
              marginal_contact_benefit=0.72, capitation_weighting=0.78, scope_flexibility=0.68, pho_transaction_cost=0.25, primary_kpi_salience=0.70, ambulance_kpi_salience=0.55, data_observability=0.68, copayment_level=0.45, copayment_protections=0.65, equity_program_strength=0.75, telehealth_integration=0.62, local_inperson_loading=0.62, ambulance_alternative_funding=0.55, budget_tightness=0.62, safety_governance=0.80, gaming_controls=0.75, direct_claiming=0.82, stakeholder_alignment=0.60, narrative_coherence=0.70),
    _scenario("P3", "Full upstream access architecture", "Benefits schedule plus top-tier primary/ambulance KPIs, strong data, rural/in-person loading, equity protections, governance and ambulance alternatives.",
              marginal_contact_benefit=0.82, capitation_weighting=0.82, scope_flexibility=0.82, pho_transaction_cost=0.18, primary_kpi_salience=0.88, ambulance_kpi_salience=0.84, hospital_political_penalty=0.62, data_observability=0.88, copayment_level=0.35, copayment_protections=0.82, equity_program_strength=0.88, telehealth_scale=0.70, telehealth_integration=0.82, local_inperson_loading=0.82, ambulance_alternative_funding=0.80, acc_activity_funding=0.72, acc_constraint=0.03, budget_tightness=0.52, safety_governance=0.92, gaming_controls=0.88, direct_claiming=0.88, stakeholder_alignment=0.78, narrative_coherence=0.88),
    _scenario("P4", "Benefits without adequate controls", "Demand-driven benefits with broad eligibility but weak controls, weak equity protection and weak integration.",
              marginal_contact_benefit=0.90, capitation_weighting=0.62, scope_flexibility=0.90, pho_transaction_cost=0.12, primary_kpi_salience=0.70, ambulance_kpi_salience=0.70, hospital_political_penalty=0.70, data_observability=0.48, copayment_level=0.65, copayment_protections=0.32, equity_program_strength=0.42, telehealth_scale=0.92, telehealth_integration=0.34, local_inperson_loading=0.25, ambulance_alternative_funding=0.62, acc_constraint=0.00, budget_tightness=0.78, safety_governance=0.42, gaming_controls=0.28, direct_claiming=0.94, stakeholder_alignment=0.30, narrative_coherence=0.35),
    _scenario("P5", "ACC activity constraint shock", "Narrow cost-containment move that constrains ACC activity funding without compensating primary care supply architecture.",
              acc_activity_funding=0.45, acc_constraint=0.60, marginal_contact_benefit=0.08, ambulance_alternative_funding=0.28, budget_tightness=0.88, stakeholder_alignment=0.30, narrative_coherence=0.25),
    _scenario("P6", "Ambulance alternatives only", "Strengthen ambulance alternative disposition pathways and KPIs while leaving most primary care funding architecture unchanged.",
              ambulance_alternative_funding=0.78, ambulance_kpi_salience=0.80, data_observability=0.62, safety_governance=0.86, gaming_controls=0.75, primary_kpi_salience=0.45, stakeholder_alignment=0.52, narrative_coherence=0.55),
    _scenario("P7", "Scope-enabled provider supply only", "Broaden provider eligibility and clinical governance without a full demand-driven benefit stream or full accountability reset.",
              scope_flexibility=0.82, safety_governance=0.88, marginal_contact_benefit=0.38, direct_claiming=0.45, pho_transaction_cost=0.38, primary_kpi_salience=0.55, data_observability=0.60, copayment_protections=0.60, stakeholder_alignment=0.50, narrative_coherence=0.58),
    _scenario("P8", "Direct claims and PHO intermediation reform only", "Reduce PHO payment-gateway friction and add direct claims, but do not materially increase eligible contact benefits.",
              direct_claiming=0.82, pho_transaction_cost=0.20, marginal_contact_benefit=0.20, data_observability=0.62, gaming_controls=0.72, safety_governance=0.80, stakeholder_alignment=0.42, narrative_coherence=0.48),
)


def scenario_input_frame(scenarios: Sequence[Scenario] = PARAMETERISED_SCENARIOS) -> pd.DataFrame:
    return pd.DataFrame([asdict(s) for s in scenarios])


def run_parameterised_game_models(scenarios: Sequence[Scenario] = PARAMETERISED_SCENARIOS) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for scenario in scenarios:
        for game_id, model in GAME_MODELS.items():
            row = model(scenario).as_row()
            rows.append(row)
    return pd.DataFrame(rows)


def run_parameterised_hybrid_model(scenarios: Sequence[Scenario] = PARAMETERISED_SCENARIOS) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for scenario in scenarios:
        row = hybrid_outcome(scenario).as_row()
        if row["funding_architecture"] == "unspecified architecture":
            row["funding_architecture"] = scenario.description
        rows.append(row)
    return pd.DataFrame(rows)


def run_parameterised_uncertainty(
    n_per_scenario: int = 1000,
    sd: float = 0.07,
    seed: int = 20260508,
    scenarios: Sequence[Scenario] = PARAMETERISED_SCENARIOS,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    rng = np.random.default_rng(seed)
    rows: list[dict[str, object]] = []
    hybrid_rows: list[dict[str, object]] = []
    for scenario in scenarios:
        for draw in range(n_per_scenario):
            perturbed = perturb_scenario(scenario, rng, sd=sd)
            params = {field: getattr(perturbed, field) for field in PARAMETER_FIELDS}
            h = hybrid_outcome(perturbed).as_row()
            h["draw"] = draw
            h.update(params)
            hybrid_rows.append(h)
            for game_id, model in GAME_MODELS.items():
                g = model(perturbed).as_row()
                g["draw"] = draw
                g.update(params)
                rows.append(g)
    return pd.DataFrame(rows), pd.DataFrame(hybrid_rows)


def summarise_parameterised_uncertainty(hybrid_draws: pd.DataFrame) -> pd.DataFrame:
    metrics = [
        "weighted_access", "weighted_provider_viability", "weighted_equity", "weighted_fiscal_control",
        "weighted_hospital_pressure", "weighted_gaming_risk", "weighted_welfare", "supply_generation_index",
        "equity_legitimacy_index", "governance_resilience_index", "hospital_deflection_index",
        "implementation_readiness_index", "fiscal_gaming_risk_index", "interaction_penalty", "hybrid_viability_score",
    ]
    rows = []
    for (sid, sname), subset in hybrid_draws.groupby(["scenario_id", "scenario_name"], sort=True):
        row = {"scenario_id": sid, "scenario_name": sname, "n_draws": subset["draw"].nunique()}
        for metric in metrics:
            values = subset[metric].astype(float)
            row[f"{metric}_mean"] = values.mean()
            row[f"{metric}_p05"] = values.quantile(0.05)
            row[f"{metric}_p50"] = values.quantile(0.50)
            row[f"{metric}_p95"] = values.quantile(0.95)
        rows.append(row)
    return pd.DataFrame(rows).round(2)


def sensitivity_by_parameter(draws: pd.DataFrame, outcome: str = "hybrid_viability_score", top_n: int = 12) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for sid, subset in draws.groupby("scenario_id", sort=True):
        y = subset[outcome].astype(float)
        for param in PARAMETER_FIELDS:
            x = subset[param].astype(float)
            if x.nunique() <= 1 or y.nunique() <= 1:
                corr = np.nan
            else:
                corr = float(np.corrcoef(x, y)[0, 1])
            rows.append({"scenario_id": sid, "outcome": outcome, "parameter": param, "correlation": corr, "abs_correlation": abs(corr) if not np.isnan(corr) else np.nan})
    df = pd.DataFrame(rows).dropna().sort_values(["scenario_id", "abs_correlation"], ascending=[True, False])
    return df.groupby("scenario_id").head(top_n).reset_index(drop=True).round(4)


_MCDA_WEIGHTS = {
    "access_supply": 12, "hospital_deflection": 12, "equity_legitimacy": 14, "rural_inperson": 9,
    "fiscal_sustainability": 12, "gaming_low_value": 10, "admin_market_entry": 8,
    "governance_safety": 10, "political_feasibility": 6, "data_accountability": 7,
}


def hybrid_informed_mcda(scenarios: Sequence[Scenario] = PARAMETERISED_SCENARIOS) -> pd.DataFrame:
    hybrid = run_parameterised_hybrid_model(scenarios)
    scenario_df = scenario_input_frame(scenarios)
    merged = hybrid.merge(scenario_df[["scenario_id", *PARAMETER_FIELDS]], on="scenario_id", how="left")
    rows = []
    total_weight = sum(_MCDA_WEIGHTS.values())
    for _, r in merged.iterrows():
        criteria = {
            "access_supply": 0.55 * float(r["supply_generation_index"]) + 0.45 * float(r["weighted_access"]),
            "hospital_deflection": float(r["hospital_deflection_index"]),
            "equity_legitimacy": float(r["equity_legitimacy_index"]),
            "rural_inperson": 100 * (0.60 * float(r["local_inperson_loading"]) + 0.20 * float(r["telehealth_integration"]) + 0.20 * float(r["ambulance_alternative_funding"])),
            "fiscal_sustainability": 0.55 * float(r["weighted_fiscal_control"]) + 0.45 * (100 - float(r["fiscal_gaming_risk_index"])),
            "gaming_low_value": 100 - float(r["fiscal_gaming_risk_index"]),
            "admin_market_entry": 100 * (0.55 * float(r["direct_claiming"]) + 0.45 * (1 - float(r["pho_transaction_cost"]))),
            "governance_safety": float(r["governance_resilience_index"]),
            "political_feasibility": 100 * (0.45 * float(r["stakeholder_alignment"]) + 0.35 * float(r["narrative_coherence"]) + 0.20 * (1 - max(0.0, float(r["copayment_level"]) - float(r["copayment_protections"])))),
            "data_accountability": 100 * (0.45 * float(r["data_observability"]) + 0.25 * float(r["primary_kpi_salience"]) + 0.20 * float(r["ambulance_kpi_salience"]) + 0.10 * float(r["gaming_controls"])),
        }
        weighted_score = sum(criteria[k] * _MCDA_WEIGHTS[k] for k in _MCDA_WEIGHTS) / total_weight
        risk_penalty = 0.16 * float(r["fiscal_gaming_risk_index"]) + 0.10 * float(r["interaction_penalty"])
        row = {
            "scenario_id": r["scenario_id"],
            "scenario_name": r["scenario_name"],
            "weighted_score_before_penalty": round(weighted_score, 2),
            "risk_penalty": round(risk_penalty, 2),
            "risk_adjusted_mcda_score": round(max(0, min(100, weighted_score - risk_penalty)), 2),
        }
        row.update({k: round(v, 2) for k, v in criteria.items()})
        rows.append(row)
    result = pd.DataFrame(rows)
    result["rank"] = result["risk_adjusted_mcda_score"].rank(ascending=False, method="min").astype(int)
    return result.sort_values(["rank", "risk_adjusted_mcda_score"], ascending=[True, False]).reset_index(drop=True)
