"""Uncertainty and calibration-readiness tools for demonstrative NZ policy games.

This module does not calibrate to empirical data. It stress-tests the stylised
v0.6.0 game models by perturbing scenario levers and identifying which inputs
most influence access, hospital pressure, gaming risk and welfare.
"""

from __future__ import annotations

from dataclasses import asdict, fields
from typing import Iterable, Sequence

import numpy as np
import pandas as pd

from .demonstrative_games import GAME_MODELS, SCENARIOS, Scenario, clip


PARAMETER_FIELDS: tuple[str, ...] = tuple(
    field.name
    for field in fields(Scenario)
    if field.name not in {"scenario_id", "name", "description"}
)


PARAMETER_PRIORS: dict[str, dict[str, object]] = {
    "marginal_contact_benefit": {
        "interpretation": "Strength of demand-driven payment for eligible primary/urgent/ambulance contact types.",
        "empirical_data_needed": "Benefit schedule design, claim rates, payment elasticity, MBS/ACC analogues.",
        "priority": "critical",
    },
    "capitation_weighting": {
        "interpretation": "Adequacy of capitation weights for need, deprivation, rurality, multimorbidity and delivery cost.",
        "empirical_data_needed": "Current and proposed capitation formula, NES enrolment data, utilisation/cost modelling.",
        "priority": "high",
    },
    "scope_flexibility": {
        "interpretation": "Extent to which claimable activity can be generated by providers other than GPs where within scope.",
        "empirical_data_needed": "Scopes of practice, prescribing rules, workforce numbers, provider productivity, substitution evidence.",
        "priority": "critical",
    },
    "pho_transaction_cost": {
        "interpretation": "Friction, delay, opacity and entry barriers caused by PHO payment intermediation.",
        "empirical_data_needed": "PHO financial flows, pass-through rules, contracting timelines, provider entry case studies.",
        "priority": "high",
    },
    "primary_kpi_salience": {
        "interpretation": "Political and managerial visibility of primary care access, continuity and co-payment indicators.",
        "empirical_data_needed": "Health target reporting, governance papers, performance dashboards, HNZ board reporting.",
        "priority": "high",
    },
    "ambulance_kpi_salience": {
        "interpretation": "Visibility of ambulance response, non-conveyance, treat-and-refer and ED interface indicators.",
        "empirical_data_needed": "Ambulance contract KPIs, response times, ramping/offload data, alternative disposition rates.",
        "priority": "high",
    },
    "hospital_political_penalty": {
        "interpretation": "Relative political/managerial penalty attached to visible hospital failure compared with upstream access failure.",
        "empirical_data_needed": "Budget papers, media analysis, ministerial targets, escalation processes, deficit responses.",
        "priority": "medium",
    },
    "data_observability": {
        "interpretation": "Ability to observe unmet need, appointment access, ambulance pathways, ED demand and avoidable hospitalisation linkages.",
        "empirical_data_needed": "NPCD, ED data, ambulance data, linked datasets, data completeness and timeliness measures.",
        "priority": "critical",
    },
    "copayment_level": {
        "interpretation": "Patient price signal and private contribution to primary care utilisation.",
        "empirical_data_needed": "Practice fee schedules, patient-reported unmet need due to cost, CSC/VLCA/age-group fee rules.",
        "priority": "critical",
    },
    "copayment_protections": {
        "interpretation": "Extent of fee caps, zero-fee groups, concessions and targeted protections for high-need patients.",
        "empirical_data_needed": "Fee cap rules, concession eligibility, patient utilisation by income/deprivation/ethnicity/rurality.",
        "priority": "critical",
    },
    "equity_program_strength": {
        "interpretation": "Strength of kaupapa Maori, Pacific, outreach, locality, trust and navigation functions.",
        "empirical_data_needed": "Programme funding, workforce, provider networks, access indicators by ethnicity/deprivation.",
        "priority": "critical",
    },
    "telehealth_scale": {
        "interpretation": "Extent of telehealth capacity and availability.",
        "empirical_data_needed": "Telehealth volumes, provider type, substitution patterns, rural uptake, continuity outcomes.",
        "priority": "medium",
    },
    "telehealth_integration": {
        "interpretation": "Integration of telehealth with local records, local teams, follow-up and in-person escalation.",
        "empirical_data_needed": "Referral pathways, shared records, continuity metrics, complaints/adverse events.",
        "priority": "high",
    },
    "local_inperson_loading": {
        "interpretation": "Payment support for local, rural and in-person capacity that telehealth cannot replace.",
        "empirical_data_needed": "Rural payment loadings, service viability, travel time, procedural and examination-dependent care data.",
        "priority": "high",
    },
    "ambulance_alternative_funding": {
        "interpretation": "Funding for hear-and-treat, treat-and-refer, non-conveyance and alternative destination pathways.",
        "empirical_data_needed": "Ambulance disposition data, clinical safety outcomes, reimbursement rules, ED avoidance estimates.",
        "priority": "high",
    },
    "acc_activity_funding": {
        "interpretation": "Extent to which ACC activity payments stabilise practice revenue and marginal supply.",
        "empirical_data_needed": "ACC claim volumes, payments by provider/practice, injury/non-injury revenue mix.",
        "priority": "high",
    },
    "acc_constraint": {
        "interpretation": "Policy or pricing constraint on ACC fee-for-service/activity payments.",
        "empirical_data_needed": "ACC schedule changes, utilisation caps, provider response, cross-sector flow effects.",
        "priority": "medium",
    },
    "budget_tightness": {
        "interpretation": "Constraint imposed by fixed envelopes, baselines, deficits and reprioritisation pressure.",
        "empirical_data_needed": "Vote Health, HNZ baselines, deficit papers, primary/community vs hospital expenditure trend.",
        "priority": "high",
    },
    "safety_governance": {
        "interpretation": "Clinical governance, credentialing, prescribing rules and audit that make scope-enabled claiming safe.",
        "empirical_data_needed": "Regulatory requirements, clinical governance models, adverse event reporting, audit mechanisms.",
        "priority": "critical",
    },
    "gaming_controls": {
        "interpretation": "Audit, data, coding rules and balancing measures that reduce low-value activity or target gaming.",
        "empirical_data_needed": "Claims audit data, coding rules, utilisation outliers, anti-fraud controls, quality indicators.",
        "priority": "critical",
    },
    "direct_claiming": {
        "interpretation": "Ability for accredited providers to claim directly through a national payment platform.",
        "empirical_data_needed": "Payment-platform specifications, credentialing rules, claims-processing costs, provider onboarding data.",
        "priority": "high",
    },
    "stakeholder_alignment": {
        "interpretation": "Degree of coalition support across providers, PHOs, Maori/Pacific providers, ambulance, HNZ, ACC and Treasury.",
        "empirical_data_needed": "Stakeholder interviews, submissions, workshop outputs, governance positions.",
        "priority": "medium",
    },
    "narrative_coherence": {
        "interpretation": "Clarity of reform framing as access/hospital-avoidance architecture rather than pro-market or sector-income claim.",
        "empirical_data_needed": "Political discourse analysis, stakeholder feedback, public communication testing.",
        "priority": "medium",
    },
}


def parameter_prior_rows() -> list[dict[str, object]]:
    """Return a register of model parameters, meanings and evidence needs."""

    rows: list[dict[str, object]] = []
    for field in PARAMETER_FIELDS:
        meta = PARAMETER_PRIORS.get(field, {})
        scenario_values = [getattr(scenario, field) for scenario in SCENARIOS]
        rows.append(
            {
                "parameter": field,
                "demonstrative_min": min(scenario_values),
                "demonstrative_max": max(scenario_values),
                "demonstrative_mean": sum(scenario_values) / len(scenario_values),
                "interpretation": meta.get("interpretation", ""),
                "empirical_data_needed": meta.get("empirical_data_needed", ""),
                "evidence_priority": meta.get("priority", "medium"),
                "calibration_status": "not calibrated; demonstrative prior only",
            }
        )
    return rows


def perturb_scenario(
    scenario: Scenario,
    rng: np.random.Generator,
    sd: float = 0.08,
    lower: float = 0.0,
    upper: float = 1.0,
) -> Scenario:
    """Return a perturbed scenario using clipped normal draws around each lever."""

    values = asdict(scenario)
    for field in PARAMETER_FIELDS:
        base = float(values[field])
        values[field] = float(np.clip(rng.normal(base, sd), lower, upper))
    return Scenario(**values)


def run_monte_carlo(
    n_per_scenario: int = 500,
    sd: float = 0.08,
    seed: int = 20260507,
    scenarios: Sequence[Scenario] = SCENARIOS,
) -> pd.DataFrame:
    """Run uncertainty draws for all scenarios and game models.

    Returns a long dataframe with one row per scenario draw and game.
    """

    rng = np.random.default_rng(seed)
    rows: list[dict[str, object]] = []
    for scenario in scenarios:
        for draw in range(n_per_scenario):
            perturbed = perturb_scenario(scenario, rng, sd=sd)
            parameter_values = {field: getattr(perturbed, field) for field in PARAMETER_FIELDS}
            for game_id, model in GAME_MODELS.items():
                outcome = model(perturbed)
                row = outcome.as_row()
                row["draw"] = draw
                row.update(parameter_values)
                rows.append(row)
    return pd.DataFrame(rows)


def summarise_uncertainty(draws: pd.DataFrame) -> pd.DataFrame:
    """Summarise uncertainty draws by scenario."""

    metrics = [
        "access_score",
        "provider_viability",
        "equity_score",
        "fiscal_control",
        "hospital_pressure",
        "gaming_risk",
        "system_welfare",
    ]
    grouped = draws.groupby(["scenario_id", "scenario_name"], sort=True)
    rows: list[dict[str, object]] = []
    for key, subset in grouped:
        scenario_id, scenario_name = key
        row: dict[str, object] = {"scenario_id": scenario_id, "scenario_name": scenario_name, "n_rows": len(subset)}
        for metric in metrics:
            values = subset[metric].astype(float)
            row[f"{metric}_mean"] = values.mean()
            row[f"{metric}_p05"] = values.quantile(0.05)
            row[f"{metric}_p50"] = values.quantile(0.50)
            row[f"{metric}_p95"] = values.quantile(0.95)
        rows.append(row)
    return pd.DataFrame(rows).round(2)


def rank_sensitivity(
    draws: pd.DataFrame,
    outcome_metric: str = "system_welfare",
    by: Sequence[str] = ("game_id", "game_name"),
    top_n: int = 8,
) -> pd.DataFrame:
    """Rank parameters by absolute Pearson correlation with an outcome metric."""

    rows: list[dict[str, object]] = []
    for keys, subset in draws.groupby(list(by), sort=True):
        if not isinstance(keys, tuple):
            keys = (keys,)
        y = subset[outcome_metric].astype(float)
        for parameter in PARAMETER_FIELDS:
            x = subset[parameter].astype(float)
            if x.nunique() <= 1 or y.nunique() <= 1:
                corr = np.nan
            else:
                corr = float(np.corrcoef(x, y)[0, 1])
            row = {name: value for name, value in zip(by, keys)}
            row.update(
                {
                    "outcome_metric": outcome_metric,
                    "parameter": parameter,
                    "correlation": corr,
                    "abs_correlation": abs(corr) if not np.isnan(corr) else np.nan,
                    "direction": "positive" if corr >= 0 else "negative",
                }
            )
            rows.append(row)
    result = pd.DataFrame(rows)
    result = result.sort_values([*by, "abs_correlation"], ascending=[True] * len(by) + [False])
    result["rank_within_game"] = result.groupby(list(by))["abs_correlation"].rank(method="first", ascending=False)
    return result[result["rank_within_game"] <= top_n].round(4)


def scenario_pairwise_probabilities(draws: pd.DataFrame) -> pd.DataFrame:
    """Estimate demonstrative probability that each scenario beats S0 on welfare and hospital pressure.

    This compares draw-level scenario means, not calibrated real-world probabilities.
    """

    draw_means = (
        draws.groupby(["scenario_id", "scenario_name", "draw"], sort=True)[["system_welfare", "hospital_pressure", "gaming_risk", "access_score"]]
        .mean()
        .reset_index()
    )
    s0 = draw_means[draw_means["scenario_id"] == "S0"].set_index("draw")
    rows: list[dict[str, object]] = []
    for scenario_id in sorted(draw_means["scenario_id"].unique()):
        if scenario_id == "S0":
            continue
        subset = draw_means[draw_means["scenario_id"] == scenario_id].set_index("draw")
        common = subset.index.intersection(s0.index)
        rows.append(
            {
                "scenario_id": scenario_id,
                "scenario_name": str(subset["scenario_name"].iloc[0]),
                "p_welfare_gt_s0": float((subset.loc[common, "system_welfare"] > s0.loc[common, "system_welfare"]).mean()),
                "p_hospital_pressure_lt_s0": float((subset.loc[common, "hospital_pressure"] < s0.loc[common, "hospital_pressure"]).mean()),
                "p_access_gt_s0": float((subset.loc[common, "access_score"] > s0.loc[common, "access_score"]).mean()),
                "p_gaming_risk_lt_s0": float((subset.loc[common, "gaming_risk"] < s0.loc[common, "gaming_risk"]).mean()),
                "comparison_status": "demonstrative uncertainty only; not empirical probability",
            }
        )
    return pd.DataFrame(rows).round(3)
